apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kmgv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kmgv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kmgv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kmgv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kmgv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-semm-tenant/rhtap-demo-app/hacbs-test-project-kmgv@sha256:010b35e33d5f5e06855e2d999b3c9ca632b71fe32adce6fdd5081006b1eb6b31
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
